package com.example.Hello.world.models;


//User.java is to authenticate each and every user

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity //table will be automatically created
@Data  //for automatic getter and setter
@AllArgsConstructor //create the data if arg given
@NoArgsConstructor //also create the data if not arg is given
@Builder //user can only enter email and pswrd, id(autogenerated value) taken care of spring boot.
@Table (name="UserTable") //while creating table in DB, table name=UserTable, in java "User" will be used
public class User {
    @NotNull
    @Id
    @GeneratedValue
    Long id;
    @Email
    String email;
    String password;

}
